### ISSUE TITLE
Version for LibreOffice etc. missing

### ISSUE THREAD

**Issue by redtux** [austriapro/ebinterface-word-plugin#2]
Unfortunately, after two years of development a Free Software version of this useful plugin is still missing.

As an 'MS Word only add-on' is excluding many SMEs that avoid using non-free software (like myself for instance), I would like to know if there are any plans by AUSTRIAPRO to work on a similar extension for LibreOffice (or similar office suites or ERPs) on GNU/Linux (to start with).

PS: Does it make sense trying to port this to Mono? Could anyone estimate how much time this might take?

(This bug is related to https://bugs.launchpad.net/ubuntu/+bug/1)

**Comment by digitalsigi** [comment]
I forwarded your inquiry to AUSTRIAPRO and will post the answer.

Technically it seems not to be feasable to make it work with LibreOffice, because the plugin is tightly bound to Microsoft VSTO Programming model for Office Extensions, see https://msdn.microsoft.com/en-us/library/ms268878.aspx?f=255&MSPPError=-2147217396 
I am not familiar with Libre/Open Office Programming Model but a quick search on the Internet did not show any similar API for those packages. This means in fact a new, fresh implementation from ground up. What I have seen, it would even be a better approach to develop such an extension in Java rather than in C#. 
So porting it to Mono won't help, I believe it would also mean to re-implement a lot of MS functionality which is part of VSTO now integrated in .NET 4.5.
To give you an impression about the effort: The project started back in 2005 on codeplex and has been moved to github in 2016. The overall effort spent so far is beyond 3 years of development.

Well, I personally don't see a relationship to the "Ubuntu bug" you mentioned, as this is not a "killer" application and limited Austria only. I won't trigger any single Linux installation. 
The source code of the Plugin is free available and published under MIT license. There are some other projects published by AUSTRIAPRO which implement eBilling based on ebInterface which can bee integrated with ERP systems. However, this is not only a programming task it requires also organisational structures, which usually require additional consulting.

**Comment by digitalsigi** [comment]
So after some discussion with AUSTRIAPRO it turns out, that there are currently no plans to implement a similiar functionality for OpenOffice / LibreOffice.
If you have the skills, you are invited to grap some code from [https://github.com/austriapro/ebinterface-web] and start a Java based implementation for OpenOffice/LibereOffice.
In this case please get in touch with me, so that I can ask AUSTRIAPRO to open a project here.
